name: Pester Tests

on: [push, pull_request]

jobs:
  test:
    name: Pester Tests
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Show PowerShell version
        shell: pwsh
        run: $PSVersionTable

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module InvokeBuild -Force -SkipPublisherCheck -Scope CurrentUser
          Install-Module Pester -Force -SkipPublisherCheck -Scope CurrentUser
          Import-Module InvokeBuild
          Import-Module Pester

      - name: Run Invoke-Build Test
        shell: pwsh
        run: |
          Invoke-Build Test
